/**
 * ChatUltra demo AI — used when the app runs as a static website (e.g. GitHub Pages)
 * and no /api/chat backend is reachable. Produces believable streamed replies so
 * every feature (chat, code cards, live preview) still works.
 */

const NEON_SNAKE = [
  "<!DOCTYPE html>",
  '<html><head><meta charset="utf-8"><title>Neon Snake</title><style>',
  "body{margin:0;background:#070a12;display:flex;flex-direction:column;align-items:center;justify-content:center;height:100vh;font-family:monospace;color:#22d3ee}",
  "canvas{border:1px solid #22d3ee44;border-radius:12px;box-shadow:0 0 40px #22d3ee22}h1{font-size:16px;letter-spacing:4px}",
  '</style></head><body><h1>NEON SNAKE</h1><canvas id="c" width="440" height="440"></canvas>',
  "<script>",
  'var cv=document.getElementById("c"),cx=cv.getContext("2d"),N=22,S=20;',
  "var sn=[{x:10,y:10}],d={x:1,y:0},food={x:15,y:15},score=0,dead=false;",
  'document.addEventListener("keydown",function(e){',
  'if(e.key==="ArrowUp"&&d.y===0)d={x:0,y:-1};if(e.key==="ArrowDown"&&d.y===0)d={x:0,y:1};',
  'if(e.key==="ArrowLeft"&&d.x===0)d={x:-1,y:0};if(e.key==="ArrowRight"&&d.x===0)d={x:1,y:0};});',
  "function place(){food={x:Math.floor(Math.random()*N),y:Math.floor(Math.random()*N)};}",
  "function step(){",
  "if(dead)return;",
  "var h={x:(sn[0].x+d.x+N)%N,y:(sn[0].y+d.y+N)%N};",
  "for(var i=0;i<sn.length;i++){if(sn[i].x===h.x&&sn[i].y===h.y){dead=true;}}",
  "sn.unshift(h);",
  "if(h.x===food.x&&h.y===food.y){score+=10;place();}else{sn.pop();}",
  'cx.fillStyle="#070a12";cx.fillRect(0,0,440,440);',
  'cx.fillStyle="#f472b6";cx.fillRect(food.x*S+3,food.y*S+3,S-6,S-6);',
  "for(var j=0;j<sn.length;j++){cx.fillStyle=j===0?\"#22d3ee\":\"#7c3aed\";cx.fillRect(sn[j].x*S+2,sn[j].y*S+2,S-4,S-4);}",
  'cx.fillStyle="#e2e8f0";cx.fillText("SCORE "+score+(dead?"  — press R":"") ,12,16);',
  'if(dead&&("r"===lastKey())){sn=[{x:10,y:10}];d={x:1,y:0};score=0;dead=false;}',
  "}",
  'function lastKey(){return window.__rk||"";}document.addEventListener("keydown",function(e){window.__rk=e.key;});',
  "setInterval(step,90);",
  "<\/script></body></html>",
].join("\n");

const MINI_LANDING = [
  "<!DOCTYPE html>",
  '<html><head><meta charset="utf-8"><title>ChatUltra Site</title><style>',
  "*{box-sizing:border-box}body{margin:0;background:#070a12;color:#e2e8f0;font-family:system-ui,sans-serif}",
  ".hero{min-height:70vh;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;background:radial-gradient(ellipse at 50% -20%,#164e63aa,transparent 60%)}",
  "h1{font-size:52px;margin:0 0 12px;background:linear-gradient(90deg,#67e8f9,#c4b5fd);-webkit-background-clip:text;background-clip:text;color:transparent}",
  "p{color:#94a3b8;max-width:520px;line-height:1.6}",
  ".cta{margin-top:24px;display:inline-block;padding:12px 28px;border-radius:999px;background:linear-gradient(90deg,#22d3ee,#8b5cf6);color:#05070d;font-weight:700;text-decoration:none}",
  ".row{display:flex;gap:16px;justify-content:center;padding:48px 20px;flex-wrap:wrap}",
  ".card{width:240px;padding:20px;border-radius:16px;border:1px solid #ffffff14;background:#0c101c}",
  "</style></head><body>",
  '<div class="hero"><h1>Built in ChatUltra</h1><p>A single-file website generated by the demo AI. Open the full ChatUltra studio to generate your own — games, portfolios, dashboards.</p><a class="cta" href="#">Get started</a></div>',
  '<div class="row"><div class="card"><h3>Lightning fast</h3><p>Static, dependency-free and instant to load.</p></div><div class="card"><h3>Dark by default</h3><p>Designed dark-first like a real code studio.</p></div><div class="card"><h3>Yours to keep</h3><p>Push any creation to GitHub with one click.</p></div></div>',
  "</body></html>",
].join("\n");

/** Pick a demo reply based on the user's prompt. */
export function demoReply(prompt: string): string {
  const p = prompt.toLowerCase();

  if (/(game|snake|pong|shooter|arcade|breakout|play)/.test(p)) {
    return (
      "Here's a complete **Neon Snake** arcade game in a single HTML file — press **Run** on the code card to play it right here (arrow keys to steer, R to restart after a crash).\n\n" +
      "```html\n" + NEON_SNAKE + "\n```\n\n" +
      "**What's inside**\n- Wrap-around walls with neon glow styling\n- Food spawning, score counter and crash detection\n- Pure canvas + vanilla JS — zero dependencies\n\nWant your own version? Ask the full ChatUltra server for e.g. *\"a wave-based space shooter with powerups\"* and it will build one from scratch."
    );
  }

  if (/(html|website|web ?site|web ?page|landing|portfolio|site|page)/.test(p)) {
    return (
      "Here's a sleek **dark landing page** in a single HTML file — hit **Run** to preview it live, then edit the code in the Canvas panel.\n\n" +
      "```html\n" + MINI_LANDING + "\n```\n\n" +
      "It uses a radial-glow hero, gradient headline and three feature cards — a solid starting point you can remix. The full ChatUltra server can generate any custom site you describe."
    );
  }

  if (/(hi|hello|hey|who are you|what can you do|help|about)/.test(p)) {
    return (
      "**Hey — I'm the ChatUltra demo assistant.**\n\n" +
      "You're viewing the static edition of **ChatUltra**, so responses come from a built-in demo brain instead of the live model API. Everything else works exactly like the real studio:\n\n" +
      "- **Live HTML preview** — ask me for a game or site below, then press *Run* on the code card\n- **Model picker** — GPT-5.2, Claude Opus 5, Claude Sonnet 4.5, Gemini 3 Pro, Luna + your own custom models\n- **Effort dial** — Low to Ultra reasoning bars\n- **Playground** — 7 game templates, external editor window, chatultra-shell terminal\n- **GitHub push** — add your token in Settings > GitHub and push projects straight to *gefrus112/chat-gpt*\n\n" +
      "Try: *\"build a snake game\"* or *\"create a dark portfolio website\"*."
    );
  }

  return (
    "**Demo mode** — I'm the built-in fallback brain of the static ChatUltra site, so my answers are canned rather than model-generated. I can still show off the whole studio:\n\n" +
    "1. **Playable builds** — say *\"build a snake game\"* and I'll return a single-file HTML game you can **Run** instantly\n2. **Websites** — say *\"make a landing page\"* for a live-previewable site\n3. **Real AI** — run the full ChatUltra server (see the repo README) and every message streams from GPT-5.2 / Claude / Gemini / Luna with your chosen effort level\n\n" +
    "Meanwhile: the **Playground** (game templates + external editor), **terminal**, **Canvas preview**, **settings** and **GitHub push** are all fully functional right here."
  );
}

/**
 * Stream a demo reply chunk-by-chunk into the UI.
 * Returns false if the stream was aborted early.
 */
export async function streamDemoReply(reply: string, onDelta: (text: string) => void, signal: AbortSignal): Promise<boolean> {
  const tokens = reply.match(/\s*\S+/g) ?? [reply];
  let out = "";
  for (let i = 0; i < tokens.length; i++) {
    if (signal.aborted) return false;
    out += tokens[i];
    // emit every few tokens for a natural typing feel
    if (i % 3 === 0 || i === tokens.length - 1) {
      onDelta(out);
      await new Promise((r) => setTimeout(r, 14));
    }
  }
  return true;
}
